### ISSUE TITLE
[documentation] 可以更新一下sql部分的文档及使用例子？

### ISSUE THREAD

**Issue by glfeng318** [MarchLiu/jaskell-core#1]
看了测试之后，简单的select跑起来没问题，但复杂一点的比如group by或子查询这些需要文档说明一下

**Comment by MarchLiu** [comment]
好呀，这部分我也在寻找对 Java/Scala代码更友好的形式，目前写复杂查询还是有些啰嗦。如果有好的想法还请不吝指教呀
